<?php
$firstpage = array(
	//"logo"=> "../img/logo.jpg",
	"logo"=> "../../../../documents/mycompany/logos/" .$logo,
	"title"=> array("Rapport Annuel du Conseiller a la Securite","Annee	$annee",$name),
	"image"=> "../img/image_doc.jpg",
);
$footer = array(
	"date"=> $daterapport,
	"adress"=> "CARBONNE Conseil & FormaPon - 25 Merlet - 33420 ESPIET"
	//"adress"=> $adresse
);
$title = array("RAPPORT ANNUEL DU CSTMD","(CONSEILLER A LA SECURITE	POUR LE TRANSPORT DE MARCHANDISES DANGEREUSES)","Conforme a l'arrete du	02 decembre 2014 modifiant l'arrete du 29 mai 2009 dit 'arrete TMD'");

//c=> content, b=> border, l=> line(center-right-left), t=> type font(italy,bold), s=> size font
$data = array(
	array(
		array(
			"c"=>"Nom de l'entreprise :",
			"x"=>10,
			"y"=>22,
			"w"=>80,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>"12"
		),
		array(
			"c"=>$name,
			"x"=>90,
			"y"=>22,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=>"Adresse du siege social de l'entreprise",
			"x"=>10,
			"y"=>30,
			"w"=>80,
			"h"=>10,
			"b"=>0,
			"l"=>"T",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>utf8_decode($adresse),
			"x"=>90,
			"y"=>30,
			"w"=>0,
			"h"=>5,
			"b"=>0,
			"l"=>"t",
			"t"=>"",
			"s"=>"10"
		)
	),
	array(
		array(
			"c"=>utf8_decode("Année	concernée par le rapport"),
			"x"=>10,
			"y"=>40,
			"w"=>80,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=> $annee,
			"x"=>90,
			"y"=>40,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"C",
			"t"=>"B",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=> utf8_decode("Ce rapport a été établi par :"),
			"x"=>10,
			"y"=>48,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=> utf8_decode($nom),
			"x"=>10,
			"y"=>56,
			"w"=>40,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=> utf8_decode($prenom),
			"x"=>50,
			"y"=>56,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=> utf8_decode($myname),
			"x"=>10,
			"y"=>65,
			"w"=>40,
			"h"=>5,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=> utf8_decode("Tél :".$mytel.	" \n Email :".$myemail),
			"x"=>50,
			"y"=>65,
			"w"=>0,
			"h"=>5,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=> utf8_decode("Fonction : Conseiller à la sécurité"),
			"x"=>10,
			"y"=>77,
			"w"=>80,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>"12"
		),
		array(
			"c"=>"Interne",
			"x"=>90,
			"y"=>77,
			"w"=>60,
			"h"=>8,
			"b"=>0,
			"l"=>"C",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>"Externe",
			"x"=>150,
			"y"=>77,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"C",
			"t"=>"B",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=> utf8_decode("Numéro de	certificat :".$certificat),
			"x"=>90,
			"y"=>84,
			"w"=>60,
			"h"=>5,
			"b"=>0,
			"l"=>"C",
			"t"=>"",
			"s"=>"11"
		),
		array(
			"c"=>utf8_decode("Date de validité : ".$datecertif),
			"x"=>150,
			"y"=>84,
			"w"=>0,
			"h"=>5,
			"b"=>0,
			"l"=>"C",
			"t"=>"",
			"s"=>"11"
		),
		array(
			"c"=>"Mode(s) de transport",
			"x"=>90,
			"y"=>94,
			"w"=>60,
			"h"=>8,
			"b"=>0,
			"l"=>"C",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>"Tous modes",
			"x"=>150,
			"y"=>94,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"C",
			"t"=>"B",
			"s"=>"11"
		),
		array(
			"c"=>utf8_decode("Et/ou	classé(s) de \nMarchandises \ndangereuses"),
			"x"=>90,
			"y"=>103,
			"w"=>60,
			"h"=>5,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>"Toutes classes",
			"x"=>150,
			"y"=>103,
			"w"=>0,
			"h"=>5,
			"b"=>0,
			"l"=>"C",
			"t"=>"B",
			"s"=>"11"
		),
		array(
			"c"=>utf8_decode("Et/ou	géographique"),
			"x"=>90,
			"y"=>120,
			"w"=>60,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>"S/O",
			"x"=>150,
			"y"=>120,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"C",
			"t"=>"",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=>utf8_decode("Visite(s)	effectuée(s) sur site(s) voir détail au	point 4.1 du présent (appendice)"),
			"x"=>10,
			"y"=>128,
			"w"=>80,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>"Nombre de	visites",
			"x"=>90,
			"y"=>128,
			"w"=>60,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>"1",
			"x"=>150,
			"y"=>128,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"C",
			"t"=>"B",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=>utf8_decode("Identite du ou des conseillers ayant éffectue la ou les visites : \n" .$prenomuser),
			"x"=>10,
			"y"=>140,
			"w"=>80,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>utf8_decode("Numéro(s) de certificat(s):"),
			"x"=>90,
			"y"=>140,
			"w"=>60,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>$certificat,
			"x"=>150,
			"y"=>140,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"C",
			"t"=>"B",
			"s"=>"12"
		),
		array(
			"c"=>utf8_decode("Date(s) de validité:"),
			"x"=>90,
			"y"=>148,
			"w"=>60,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>$datecertif,
			"x"=>150,
			"y"=>148,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"C",
			"t"=>"B",
			"s"=>"12"
		),
		array(
			"c"=>"Signature(s) :",
			"x"=>90,
			"y"=>156,
			"w"=>60,
			"h"=>5,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>"",
			"x"=>150,
			"y"=>156,
			"w"=>0,
			"h"=>5,
			"b"=>0,
			"l"=>"C",
			"t"=>"B",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=>utf8_decode("Rapport annuel établi le :" .$daterapport),
			"x"=>10,
			"y"=>170,
			"w"=>80,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>utf8_decode("Transmis à l'entreprise le :"),
			"x"=>90,
			"y"=>170,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			"c"=>"A: Interlocuteur	CSTMD",
			"x"=>90,
			"y"=>178,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		)
	),
	array(
		array(
			"c"=>utf8_decode("Signature	du conseiller à la sécurité"),
			"x"=>10,
			"y"=>186,
			"w"=>80,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		),
		array(
			//"c"=>$signuser,
			"c"=>"",
			"x"=>90,
			"y"=>186,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>"12"
		)
	),
	array(
		array(
			//"c"=>utf8_decode("Le conseiller à la sécurité s'assure de la réception du présent rapport annuel et en conserve une trace par tout moyen approprié. Le présent rapport est à lire par le responsable de l'entreprise et à conserver pendant 5 ans à disposions des organismes de contrôles. Ce	rapport	est	conforme a l'arrêté du 29 mai 2009 modifié par l'arrêté du 02 decembre 2014 avec les ameliorations preconisees par l'ANCS (Association Nationale des CSTMD)"),
			"c"=>"",
			"x"=>10,
			"y"=>200,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>"12"
		)
	)
);
$page3 = array(
	
	array(utf8_decode("Le conseiller à la sécurité s'assure de la réception du présent rapport annuel et en conserve une trace par tout moyen approprié. Le présent rapport est à lire par le responsable de l'entreprise et à conserver pendant 5 ans à disposions des organismes de contrôles. Ce	rapport	est	conforme a l'arrêté du 29 mai 2009 modifié par l'arrêté du 02 decembre 2014 avec les ameliorations preconisees par l'ANCS (Association Nationale des CSTMD"),""),
	array(utf8_decode($synthrapport)," 5")
	
);

$page4 = array(
	array('c'=>utf8_decode("1. 1. Organisation de l'entreprise pour les activités liées au transport de marchandises dangereuses"), 'h'=>8, 's'=>12, 't'=>"B" ,'ln'=>"" ),
	array('c'=>utf8_decode("1.1. Gestion administrative et opérationnelle des activités liées au transport"), 'h'=>8, 's'=>12, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode("1.1.1 Activité de l'entreprise"), 'h'=>8, 's'=>12, 't'=>"B" ,'ln'=>"" ),
	array('c'=>$activiteclient, 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode("1.1.2 Organisation et équipements"), 'h'=>8, 's'=>12, 't'=>"B" ,'ln'=>"" ),
	array('c'=>utf8_decode($orgaclient), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode("1.2. Place du conseiller à la sécurité dans l'organisation"), 'h'=>8, 's'=>12, 't'=>"B" ,'ln'=>"" ),
	array('c'=>utf8_decode("1.2.1 Interlocuteur du Conseiller à la sécurité ou Organigramme"), 'h'=>8, 's'=>12, 't'=>"B" ,'ln'=>"" ),
	array('c'=>utf8_decode("L'entreprise dispose d'un conseiller à la sécurité externe toutes classes en relation avec"), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode($prenomuser), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode($modeuser), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode($classuser), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode("Ce conseiller à la sécurité est lié par un contrat et déclaré auprès de la DREAL"), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode($drealnom), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode($drealaddress), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode($drealcpville), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode("1.2.2 Organisation par rapport à la sûreté"), 'h'=>8, 's'=>12, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode($suretehrtxt), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	);
/*
$page5 = array(
	array('c'=>utf8_decode("2. Relevé des activités de l'année écoulée"), 'h'=>8, 's'=>12, 't'=>"B" ,'ln'=>"" ),
	array('c'=>utf8_decode("2.1. Chiffres de l'année concernée par le rapport"), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
	array('c'=>utf8_decode("2.1.1. Marchandises emballées"), 'h'=>8, 's'=>10, 't'=>"" ,'ln'=>"" ),
);
*/

$pages = array(
	//pages
	array(
		//info
		array(
			"c"=>utf8_decode("2. Relevé des activités de l'année écoulée"),
			"x"=>10,
			"y"=>22,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>16,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("2.1. Chiffres de l'année concernée par le rapport"),
			"x"=>10,
			"y"=>30,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("2.1.1. Marchandises emballées"),
			"x"=>10,
			"y"=>38,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		// start table 1 page 5
		array(
			"c"=>utf8_decode("Classe (1)"),
			"x"=>10,
			"y"=>45,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Etiquette (2)"),
			"x"=>60,
			"y"=>45,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Type de conditionnement (6)"),
			"x"=>110,
			"y"=>45,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>9,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Quantités totales annuelles (4)"),
			"x"=>155,
			"y"=>45,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>9,
			"m"=>0
		),
		array(
			"c"=>html_entity_decode($a_classe),
			"x"=>10,
			"y"=>55,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>html_entity_decode($a_etiquette),
			"x"=>60,
			"y"=>55,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>html_entity_decode($a_conditionnement),
			"x"=>110,
			"y"=>55,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>html_entity_decode($a_quantite),
			"x"=>155,
			"y"=>55,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		
	
		// End table 1 page 5
		array(
			"c"=>utf8_decode("2.1.2	Marchandises dangereuses chargées ou remplies"),
			"x"=>10,
			"y"=>150,
			"w"=>150,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
	
		
		
		
		
		//start table 2 page 5
		array(
			"c"=>"Classe (1)",
			"x"=>10,
			"y"=>160,
			"w"=>40,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"Etiquette (2)",
			"x"=>50,
			"y"=>160,
			"w"=>35,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"Type de contenant (5)",
			"x"=>85,
			"y"=>160,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"Colis",
			"x"=>85,
			"y"=>170,
			"w"=>16,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"Vrac",
			"x"=>101,
			"y"=>170,
			"w"=>16,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"Citerne",
			"x"=>117,
			"y"=>170,
			"w"=>18,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Quantités totales annuelles (3)"),
			"x"=>135,
			"y"=>160,
			"w"=>65,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"R",
			"x"=>135,
			"y"=>170,
			"w"=>22,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"F",
			"x"=>157,
			"y"=>170,
			"w"=>22,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"N",
			"x"=>179,
			"y"=>170,
			"w"=>21,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		
			
		
		array(
			"c"=>utf8_decode($b_classe),
			"x"=>10,
			"y"=>180,
			"w"=>40,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
			array(
			"c"=>utf8_decode($b_etiquette),
			"x"=>50,
			"y"=>180,
			"w"=>35,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($b_colis),
			"x"=>85,
			"y"=>180,
			"w"=>16,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($b_vrac),
			"x"=>101,
			"y"=>180,
			"w"=>16,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($b_citerne),
			"x"=>117,
			"y"=>180,
			"w"=>18,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($b_R),
			"x"=>135,
			"y"=>180,
			"w"=>22,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($b_F),
			"x"=>157,
			"y"=>180,
			"w"=>22,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($b_N),
			"x"=>179,
			"y"=>180,
			"w"=>21,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		),
	
	/// debut page 6
	
	
	//debut tableau 1 page 6
	
	
	array(
		array(
			"c"=>utf8_decode("2.1.3	Marchandises dangereuses transportées"),
			"x"=>10,
			"y"=>10,
			"w"=>0,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>"2.1.3.1 Mode routier",
			"x"=>15,
			"y"=>20,
			"w"=>0,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		// Begin table 3 page 5
		array(
			"c"=>"Classe (1)",
			"x"=>10,
			"y"=>30,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"Etiquette (2)",
			"x"=>60,
			"y"=>30,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Quantités totales annuelles (3)"),
			"x"=>110,
			"y"=>30,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"Colis",
			"x"=>110,
			"y"=>40,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"Vrac",
			"x"=>140,
			"y"=>40,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>"Citerne",
			"x"=>170,
			"y"=>40,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>utf8_decode($c_classe),
			"x"=>10,
			"y"=>50,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($c_etiquette),
			"x"=>60,
			"y"=>50,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($c_colis),
			"x"=>110,
			"y"=>50,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($c_vrac),
			"x"=>140,
			"y"=>50,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($c_citerne),
			"x"=>170,
			"y"=>50,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		//end tableau 3 page 5
		
		array(
			"c"=>"2.1.3.2 Mode ferroviaire",
			"x"=>15,
			"y"=>140,
			"w"=>0,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		// begin tableau 4 page 5
		
		array(
			"c"=>"Classe (1)",
			"x"=>10,
			"y"=>150,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Etiquette (2)",
			"x"=>60,
			"y"=>150,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Quantités totales annuelles (4)"),
			"x"=>110,
			"y"=>150,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Wagons",
			"x"=>110,
			"y"=>160,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"UTI",
			"x"=>155,
			"y"=>160,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode($d_classe),
			"x"=>10,
			"y"=>170,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($d_etiquette),
			"x"=>60,
			"y"=>170,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($d_wagon),
			"x"=>110,
			"y"=>170,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($d_uti),
			"x"=>155,
			"y"=>170,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		),
		// BEGIN PAGE 7
	array(
		array(
			"c"=>utf8_decode("2.1.3.3 Par voies de navigation intérieures"),
			"x"=>15,
			"y"=>10,
			"w"=>0,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		
		// begin tableau 5 page 5
		
				
		array(
			"c"=>"Classe (1)",
			"x"=>10,
			"y"=>20,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>"Etiquette (2)",
			"x"=>60,
			"y"=>20,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("Quantités totales annuelles (5)"),
			"x"=>110,
			"y"=>20,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("Bateau à cargaison sèche"),
			"x"=>110,
			"y"=>30,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("Bateau Citerne"),
			"x"=>155,
			"y"=>30,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($e_classe),
			"x"=>10,
			"y"=>40,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($e_etiquette),
			"x"=>60,
			"y"=>40,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($e_bateau),
			"x"=>110,
			"y"=>40,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($e_citerne),
			"x"=>155,
			"y"=>40,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		// end tableau 5 page 5
		

	
	/// debut page 6
	
	
	//debut tableau 1 page 6
	
	
	
		array(
			"c"=>utf8_decode("2.1.4 Marchandises dangereuses déchargées"),
			"x"=>10,
			"y"=>130,
			"w"=>0,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>12,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("Le relevé des activités de déchargement comprend au minimum les informations contenues dans le tableau présenté ci-dessous"),
			"x"=>15,
			"y"=>140,
			"w"=>0,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>8,
			"m"=>1
		),
		
	array(
			"c"=>"Classe",
			"x"=>10,
			"y"=>150,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Etiquette",
			"x"=>60,
			"y"=>150,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Quantités totales annuelles"),
			"x"=>110,
			"y"=>150,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"R",
			"x"=>110,
			"y"=>160,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"F",
			"x"=>140,
			"y"=>160,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"N",
			"x"=>170,
			"y"=>160,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode($f_classe),
			"x"=>10,
			"y"=>170,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($f_etiquette),
			"x"=>60,
			"y"=>170,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($f_R),
			"x"=>110,
			"y"=>170,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($f_F),
			"x"=>140,
			"y"=>170,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($f_N),
			"x"=>170,
			"y"=>170,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
	
	),

		// BEGIN PAGE 8
	array(	
		
		array(
			'c'=>utf8_decode("2.1.5 Marchandises dangereuses expédiées"),
			"x"=>10,
			"y"=>10,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>12,
			"m"=>1
		),
		
		
		array(
			"c"=>utf8_decode("2.1.5.1 Mode routier"),
			"x"=>15,
			"y"=>20,
			"w"=>0,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		// debut tableau 2 page 6
		
		
	array(
			"c"=>"Classe",
			"x"=>10,
			"y"=>30,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Etiquette",
			"x"=>60,
			"y"=>30,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Quantités totales annuelles"),
			"x"=>110,
			"y"=>30,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Colis",
			"x"=>110,
			"y"=>40,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Vrac",
			"x"=>140,
			"y"=>40,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Citerne",
			"x"=>170,
			"y"=>40,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode($g_classe),
			"x"=>10,
			"y"=>50,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($g_etiquette),
			"x"=>60,
			"y"=>50,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($g_colis),
			"x"=>110,
			"y"=>50,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($g_vrac),
			"x"=>140,
			"y"=>50,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($g_citerne),
			"x"=>170,
			"y"=>50,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		//END tableau 2 page6
		
		array(
			"c"=>utf8_decode("2.1.5.2 Mode ferroviaire"),
			"x"=>15,
			"y"=>140,
			"w"=>0,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
	
		//begin tableau 3 page 6
		
		array(
			"c"=>"Classe",
			"x"=>10,
			"y"=>150,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Etiquette",
			"x"=>60,
			"y"=>150,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Quantités totales annuelles"),
			"x"=>110,
			"y"=>150,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Wagons",
			"x"=>110,
			"y"=>160,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"UTI",
			"x"=>155,
			"y"=>160,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode($h_classe),
			"x"=>10,
			"y"=>170,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($h_etiquette),
			"x"=>60,
			"y"=>170,
			"w"=>50,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($h_wagon),
			"x"=>110,
			"y"=>170,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($h_uti),
			"x"=>155,
			"y"=>170,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		),
		// begin page 9
	array(	
		array(
			"c"=>utf8_decode("2.1.5.3 Par voie de navigation intérieures"),
			"x"=>15,
			"y"=>10,
			"w"=>0,
			"h"=>10,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		// BEGIN tableau 4 page 6
		
		array(
			"c"=>"Classe",
			"x"=>10,
			"y"=>20,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>"Etiquette",
			"x"=>60,
			"y"=>20,
			"w"=>50,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Quantités totales annuelles"),
			"x"=>110,
			"y"=>20,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Bateau à cargaison sèche"),
			"x"=>110,
			"y"=>30,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>utf8_decode("Bateau-citerne"),
			"x"=>155,
			"y"=>30,
			"w"=>45,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>0
		),
		array(
			"c"=>utf8_decode($i_classe),
			"x"=>10,
			"y"=>40,
			"w"=>50,
			"h"=>5,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($i_etiquette),
			"x"=>60,
			"y"=>40,
			"w"=>50,
			"h"=>5,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($i_bateau),
			"x"=>110,
			"y"=>40,
			"w"=>45,
			"h"=>5,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			"c"=>utf8_decode($i_citerne),
			"x"=>155,
			"y"=>40,
			"w"=>45,
			"h"=>5,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		array(
			"c"=>utf8_decode("(1) Indiquer la classe"),
			"x"=>15,
			"y"=>240,
			"w"=>0,
			"h"=>7,
			"b"=>0,
			"l"=>"",
			"t"=>"",
			"s"=>7,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("(2) Colonne a remplir obligatoirement dans le cas de la classe 7"),
			"x"=>15,
			"y"=>243,
			"w"=>0,
			"h"=>7,
			"b"=>0,
			"l"=>"",
			"t"=>"",
			"s"=>7,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("(3) Indiquer les quantités de marchandises concernées"),
			"x"=>15,
			"y"=>246,
			"w"=>0,
			"h"=>7,
			"b"=>0,
			"l"=>"",
			"t"=>"",
			"s"=>7,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("(4) Indiquer les quantités de marchandises concernées en fonction du mode de transport (R:route F:ferroviaire N:voies de navigations intérieures"),
			"x"=>15,
			"y"=>249,
			"w"=>0,
			"h"=>7,
			"b"=>0,
			"l"=>"",
			"t"=>"",
			"s"=>7,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("(5) Indiquer les quantités de marchandises concernées selon qu'il s'agit de wagons et ou d'UTI (unités de transport intermodales)"),
			"x"=>15,
			"y"=>253,
			"w"=>0,
			"h"=>7,
			"b"=>0,
			"l"=>"",
			"t"=>"",
			"s"=>7,
			"m"=>1
		),
		array(
			"c"=>utf8_decode("(5) Indiquer les quantités de marchandises concernées en fonction du type de bateau utilisé"),
			"x"=>15,
			"y"=>256,
			"w"=>0,
			"h"=>7,
			"b"=>0,
			"l"=>"",
			"t"=>"",
			"s"=>7,
			"m"=>1
		),
		
		
	),
	
	
	//////// PAGE 7
	
	array(
		//info page 7
		array(
			'c'=>"2.2 Marchandises dangereuses a haut risque",
			"x"=>10,
			"y"=>30,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>16,
			"m"=>1
		),
		
		//Start table 1 page 7
		array(
			'c'=>utf8_decode("L'entreprise est-elle concernée par les marchandises reprises dans le tableau du 1.10.3.1.2 ?"),
			"x"=>10,
			"y"=>45,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$marchandise110312oui,
			"x"=>10,
			"y"=>55,
			"w"=>95,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$marchandise110312non,
			"x"=>105,
			"y"=>55,
			"w"=>95,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("L'entreprise est-elle concernée par les marchandises reprises dans le tableau du 1.10.3.1.3 ?"),
			"x"=>10,
			"y"=>65,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$marchandise110313oui,
			"x"=>10,
			"y"=>75,
			"w"=>95,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$marchandise110313non,
			"x"=>105,
			"y"=>75,
			"w"=>95,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Si oui, activité (s) concernée (s)"),
			"x"=>10,
			"y"=>85,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>"Emballeur",
			"x"=>10,
			"y"=>95,
			"w"=>47,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$emballeurx,
			"x"=>57,
			"y"=>95,
			"w"=>48,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>"Remplisseur",
			"x"=>105,
			"y"=>95,
			"w"=>47,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$remplisseurx,
			"x"=>152,
			"y"=>95,
			"w"=>48,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Expéditeur"),
			"x"=>10,
			"y"=>105,
			"w"=>47,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$expediteurx,
			"x"=>57,
			"y"=>105,
			"w"=>48,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>"Chargeur",
			"x"=>105,
			"y"=>105,
			"w"=>47,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$chargeurx,
			"x"=>152,
			"y"=>105,
			"w"=>48,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>"Destinataire",
			"x"=>10,
			"y"=>115,
			"w"=>47,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$destinatairex,
			"x"=>57,
			"y"=>115,
			"w"=>48,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>"Transporteur",
			"x"=>105,
			"y"=>115,
			"w"=>47,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$transporteurx,
			"x"=>152,
			"y"=>115,
			"w"=>48,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Déchargeur"),
			"x"=>10,
			"y"=>125,
			"w"=>47,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$dechargeurx,
			"x"=>57,
			"y"=>125,
			"w"=>48,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>"",
			"x"=>105,
			"y"=>125,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Autre (à préciser)"),
			"x"=>10,
			"y"=>135,
			"w"=>95,
			"h"=>20,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$autre,
			"x"=>105,
			"y"=>135,
			"w"=>0,
			"h"=>20,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Préciser, le cas échéant, les marchandises dangereuses et/ou classes de danger concernées, et en cas de pluralité, le(s) site(s) concerné(s):"),
			"x"=>10,
			"y"=>155,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("L'entreprise est elle soumise au plan de sûreté prévu au 1.10.3.2 ?"),
			"x"=>10,
			"y"=>165,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$plan11032oui,
			"x"=>10,
			"y"=>175,
			"w"=>95,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$plan11032non,
			"x"=>105,
			"y"=>175,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Si oui est-il établi"),
			"x"=>10,
			"y"=>185,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$planetablioui,
			"x"=>10,
			"y"=>195,
			"w"=>95,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$planetablinon,
			"x"=>105,
			"y"=>195,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$planremarque,
			"x"=>10,
			"y"=>205,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Le cas échéant pour les matières radioactives, les dispositions du 1.10.5 sont-elles respectées"),
			"x"=>10,
			"y"=>215,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$disposition1105oui,
			"x"=>10,
			"y"=>225,
			"w"=>95,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>$disposition1105non,
			"x"=>105,
			"y"=>225,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		//END table 1 page 7
	),
	
	
	/////// page 8
	
	
	
	
	array(
		//info page 8
		
		array(
			'c'=>utf8_decode("2.3 Dispositions relatives aux parcs de stationnement selon le 2.3.2 de l'annexe 1 du présent arrêté L'entreprise dispose-t-elle de parcs de stationnement soumis aux exigences du 2.3.2 ?"),
			"x"=>10,
			"y"=>10,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("Si oui, nombre de parc de stationnement :"),
			"x"=>10,
			"y"=>30,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>1
		),
		
		
		
		array(
			'c'=>utf8_decode("3 Déclarations, rapports, résumé et bilan des différents évènements et/ou accidents"),
			"x"=>10,
			"y"=>40,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>14,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("Rappel : En application des acticles 6 et 7 de l'arrêté TMD, tout accident répondant au 1.8.3.6 doit faire l'objet d'un rapport d'accident, par les conseillers à la sécurité concernés, accompagné d'une analyse des causes et de recommandations écrites visant à éviter le renouvellement de tels accidents"),
			"x"=>10,
			"y"=>60,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("Lorsque ces accidents ont répondu aux critères de déclaration d'évènements selon le chapitre 1.8.5.3, le rapport d'accident doit être transmis aux autorités concernées, dans un délai d'un mois"),
			"x"=>10,
			"y"=>90,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("Les accidents répondant aux critères de déclaration d'évènements impliquant des matières dangereuses selon le chapitre 1.8.5.3 sont résumés dans les tableaux ci-dessous"),
			"x"=>10,
			"y"=>110,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("R = route, F = Fer, N = Fluvial"),
			"x"=>10,
			"y"=>130,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("C = chargement, D= déchargement, T = transport, E = emballage, Tb = transbordement"),
			"x"=>10,
			"y"=>140,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("En cas de perte de la ou les marchandise(s) dangereuse(s)"),
			"x"=>10,
			"y"=>150,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("Critère 1 : dommages corporels"),
			"x"=>10,
			"y"=>160,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("Critère 2 : perte de marchandise dangereuse"),
			"x"=>10,
			"y"=>170,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("Critère 3 : dommages matériels ou à l'environnement,"),
			"x"=>10,
			"y"=>180,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("Critère 4 : intervention des autorités."),
			"x"=>10,
			"y"=>190,
			"w"=>0,
			"h"=>6,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
	),
		
	
	///////// Page 9
	
	
	
	
	
	array(
		//info page 9
		array(
			'c'=>utf8_decode("3.1 Evènements soumis à déclaration au titre de l'article 7 du présent arrêté (accidents déclarés)"),
			"x"=>10,
			"y"=>20,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>16,
			"m"=>1
		),
		array(
			'c'=>"Date",
			"x"=>10,
			"y"=>40,
			"w"=>20,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>"Lieu",
			"x"=>30,
			"y"=>40,
			"w"=>20,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Mode concerné"),
			"x"=>50,
			"y"=>40,
			"w"=>21,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"R",
			"x"=>50,
			"y"=>50,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"F",
			"x"=>57,
			"y"=>50,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"N",
			"x"=>64,
			"y"=>50,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Opération concernée"),
			"x"=>71,
			"y"=>40,
			"w"=>42,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"C",
			"x"=>71,
			"y"=>50,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"D",
			"x"=>78,
			"y"=>50,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"T",
			"x"=>85,
			"y"=>50,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"E",
			"x"=>92,
			"y"=>50,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"Re",
			"x"=>99,
			"y"=>50,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"Ex",
			"x"=>106,
			"y"=>50,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
				
		array(
			'c'=>utf8_decode("Marchandises dangereuses"),
			"x"=>113,
			"y"=>40,
			"w"=>30,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>6,
			"m"=>0
		),
		
		array(
			'c'=>utf8_decode("Quantités impliquées"),
			"x"=>143,
			"y"=>40,
			"w"=>30,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Critère du 1.8.5"),
			"x"=>173,
			"y"=>40,
			"w"=>20,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>6,
			"m"=>0
		),
		array(
			'c'=>"1",
			"x"=>173,
			"y"=>50,
			"w"=>5,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"2",
			"x"=>178,
			"y"=>50,
			"w"=>5,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"3",
			"x"=>183,
			"y"=>50,
			"w"=>5,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"4",
			"x"=>188,
			"y"=>50,
			"w"=>5,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>0
		),
		
		
		////data tableau
		
		array(
			'c'=>$j_date,
			"x"=>10,
			"y"=>60,
			"w"=>20,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>$j_lieu,
			"x"=>30,
			"y"=>60,
			"w"=>20,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		array(
			'c'=>$j_r,
			"x"=>50,
			"y"=>60,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_f,
			"x"=>57,
			"y"=>60,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_n,
			"x"=>64,
			"y"=>60,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		
		array(
			'c'=>$j_c,
			"x"=>71,
			"y"=>60,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_d,
			"x"=>78,
			"y"=>60,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_t,
			"x"=>85,
			"y"=>60,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_e,
			"x"=>92,
			"y"=>60,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_re,
			"x"=>99,
			"y"=>60,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_ex,
			"x"=>106,
			"y"=>60,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_marchandises,
			"x"=>113,
			"y"=>60,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>6,
			"m"=>1
		),
		
		array(
			'c'=>$j_quantites,
			"x"=>143,
			"y"=>60,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>1
		),
		
		array(
			'c'=>$j_critere1,
			"x"=>173,
			"y"=>60,
			"w"=>5,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_critere2,
			"x"=>178,
			"y"=>60,
			"w"=>5,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_critere3,
			"x"=>183,
			"y"=>60,
			"w"=>5,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$j_critere4,
			"x"=>188,
			"y"=>60,
			"w"=>5,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>1
		),
		
				
		//////// tableau accident
		
		
		array(
			'c'=>utf8_decode("3.2 Accidents soumis à la rédaction d'un rapport d'accident au titre du 4 de l'article 6 du présent arrêté"),
			"x"=>10,
			"y"=>120,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>16,
			"m"=>1
		),
		
		array(
			'c'=>"Date",
			"x"=>10,
			"y"=>140,
			"w"=>20,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>"Lieu",
			"x"=>30,
			"y"=>140,
			"w"=>20,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Mode concerné"),
			"x"=>50,
			"y"=>140,
			"w"=>21,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"R",
			"x"=>50,
			"y"=>150,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"F",
			"x"=>57,
			"y"=>150,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"N",
			"x"=>64,
			"y"=>150,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Opération concernée"),
			"x"=>71,
			"y"=>140,
			"w"=>42,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"C",
			"x"=>71,
			"y"=>150,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"D",
			"x"=>78,
			"y"=>150,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"T",
			"x"=>85,
			"y"=>150,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"E",
			"x"=>92,
			"y"=>150,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"Re",
			"x"=>99,
			"y"=>150,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
		array(
			'c'=>"Ex",
			"x"=>106,
			"y"=>150,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>0
		),
				
		array(
			'c'=>utf8_decode("Marchandises dangereuses"),
			"x"=>113,
			"y"=>140,
			"w"=>40,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>6,
			"m"=>0
		),
		
		array(
			'c'=>utf8_decode("Quantités impliquées"),
			"x"=>153,
			"y"=>140,
			"w"=>40,
			"h"=>20,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>0
		),
		
		//// data tableau accidents
		
		array(
			'c'=>$k_date,
			"x"=>10,
			"y"=>160,
			"w"=>20,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>$k_lieu,
			"x"=>30,
			"y"=>160,
			"w"=>20,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		array(
			'c'=>$k_r,
			"x"=>50,
			"y"=>160,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$k_f,
			"x"=>57,
			"y"=>160,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$k_n,
			"x"=>64,
			"y"=>160,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		
		array(
			'c'=>$k_c,
			"x"=>71,
			"y"=>160,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$k_d,
			"x"=>78,
			"y"=>160,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$k_t,
			"x"=>85,
			"y"=>160,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$k_e,
			"x"=>92,
			"y"=>160,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$k_re,
			"x"=>99,
			"y"=>160,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$k_ex,
			"x"=>106,
			"y"=>160,
			"w"=>7,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"B",
			"s"=>8,
			"m"=>1
		),
		array(
			'c'=>$k_marchandises,
			"x"=>113,
			"y"=>160,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>6,
			"m"=>1
		),
		
		array(
			'c'=>$k_quantites,
			"x"=>143,
			"y"=>160,
			"w"=>30,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>8,
			"m"=>1
		),
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		),
	
	
	///// Page 13
	array(
		
		array(
			'c'=>utf8_decode("3.3 Evènements relatifs au transport de marchandises dangereuses de la classe 7"),
			"x"=>10,
			"y"=>140,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>16,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("Nombre d'évènements significatifs :"),
			"x"=>10,
			"y"=>160,
			"w"=>95,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Nombre d'évènements intéressants (EIT)(*):"),
			"x"=>105,
			"y"=>160,
			"w"=>95,
			"h"=>10,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("Aucun accident déclaré cette année"),
			"x"=>10,
			"y"=>170,
			"w"=>0,
			"h"=>10,
			"b"=>1,
			"l"=>"C",
			"t"=>"",
			"s"=>12,
			"m"=>0
		),
		array(
			'c'=>utf8_decode("(*) EIT : Ecarts aux exigences réglementaires qui n'entraînent pas de dégradation des fonctions de sûreté et dont les incidences sont faibles. Ces EIT sont alors classés hors échelle sur l'échelle INES et ne nécessitent pas de compte rendu d'évènement significatif"),
			"x"=>10,
			"y"=>180,
			"w"=>0,
			"h"=>8,
			"b"=>1,
			"l"=>"L",
			"t"=>"",
			"s"=>7,
			"m"=>1
		),
	),
	
	
	///// Page 10
	array(
		array(
			'c'=>utf8_decode("4 Bilan des interventions réalisées au titre des activités liées au transport de marchandises dangereuses "),
			"x"=>10,
			"y"=>10,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"B",
			"s"=>14,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("4.1 Tableau de synthèse des visites et interventions réalisées par le conseiller à la sécurité"),
			"x"=>10,
			"y"=>30,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		array(
			'c'=>utf8_decode("4.2 Rappel des autres travaux ou audits réalisés pouvant avoir une incidence sur les activités liées au transport de marchandises dangereuses"),
			"x"=>10,
			"y"=>100,
			"w"=>0,
			"h"=>8,
			"b"=>0,
			"l"=>"L",
			"t"=>"",
			"s"=>10,
			"m"=>1
		),
		
		
		
		
		
		
		
		
		
		
	),
	
	
	
	
	
);